name: Publish .NET MAUI Application on Tag

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [arm64, x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install .NET MAUI workload
        run: dotnet workload install maui

      - name: Build project for ${{ matrix.architecture }}
        run: dotnet publish -f net9.0-maccatalyst -c Release -o output/${{ matrix.architecture }}

      - name: Get Release
        id: get_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS .app files
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/${{ matrix.architecture }}/Imago.app
          asset_name: Imago-${{ matrix.architecture }}.app
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
